### ISSUE TITLE
Liferay can't find portlet in WAR

### ISSUE THREAD

**Issue by pleimann** [pleimann/angular-ray#1]

**Comment by pleimann** [comment]
Create a new Gradle Liferay project that will deploy to Liferay.

**Comment by Mrfoofums** [comment]
In order for Liferay to see a Portlet, you have to create a portlet within the project. Within the project you will see 2 portlets, 1 named New, and another Angulart Portlet. 

I also have it working with both gradle and maven, now is to get Angular to show up in the view.
