### ISSUE TITLE
Angular client is not starting

### ISSUE THREAD

**Issue by pleimann** [pleimann/angular-ray#2]
There are two JSPs - one in .../webapp/WEB-INF/jsp and one in .../webapp/html/angular. portlet.xml file is configured to use .../webapp/html/angular/view.jsp which doesn't have the JS code to bootstrap Angular.

**Comment by Mrfoofums** [comment]
I thought Liferay.portlet.ready() accounted for that. 

Also, Liferay.on() might be the answer. I suppose we could simply move it into the child JSP.

https://dev.liferay.com/develop/tutorials/-/knowledge_base/6-1/javascript
